### PR TITLE
OTP Configuration

### PR DESCRIPTION
**Pull request by Sodeeqishola5**
Can you review and merge it boss

### CODE REVIEW

**Review by iamkelv — APPROVED** [review]
Thank @Sodeeqishola5  for the job well-done can you work on the SMS Template and the Set OTP Crendential page

**Comment by Sodeeqishola5** [comment]
Ok sir, I will. Hope I've merged successfully now?

**Comment by Sodeeqishola5** [comment]
> Thank @Sodeeqishola5 for the job well-done can you work on the SMS Template and the Set OTP Crendential page

I've completed OTP credentials but SMS Template remain router and small UI amendment

**Comment by iamkelv** [comment]
> > Thank @Sodeeqishola5 for the job well-done can you work on the SMS Template and the Set OTP Crendential page
> 
> I've completed OTP credentials but SMS Template remain router and small UI amendment

so when are you finishing it?

**Comment by Sodeeqishola5** [comment]
> > > Thank @Sodeeqishola5 for the job well-done can you work on the SMS Template and the Set OTP Crendential page
> > 
> > I've completed OTP credentials but SMS Template remain router and small UI amendment
> 
> so when are you finishing it?

Before Monday by God grace

**Pull request closed without merging**
