### PR TITLE
Added the affiliate page

### PR DESCRIPTION
**Pull request by HedrisTemmyTop**
Added the affiliate page, implemented nested  routing in the users team. edited the dashboard and some other component to look fit

### CODE REVIEW

**Comment by iamkelv** [comment]
Thank @HedrisTemmyTop  since the issue you work on is for the user dashboard I have assigned the review to @debbyuzuegbu  since she is the one leading the team. Thank you

**Comment by debbyuzuegbu** [comment]
oh just seeing this. @iamkelv

**Comment by HedrisTemmyTop** [comment]
Yeah

**Review by debbyuzuegbu — COMMENTED** [review]
Hi @HedrisTemmyTop Please kindly push the new one has discussed. Thank you. Would close this one.

**Pull request closed without merging**
